Fix build error on amlogic
:Release Notes:
Some eglplatform.h doesn't have proper typedef for gbm surface.

:Detailed Notes:
http://gecko.lge.com:8000/Errors/Details/867510
git/drmplanes/drm-common.c:361:74: error: passing argument 3 of 'eglCreateWindowSurface' from incompatible pointer type [-Werror=incompatible-pointer-types]
git/drmplanes/drm-common.c:367:74: error: passing argument 3 of 'eglCreateWindowSurface' from incompatible pointer type [-Werror=incompatible-pointer-types]
git/drmplanes/drm-gldraw-atomic.c:498:73: error: passing argument 3 of 'eglCreateWindowSurface' from incompatible pointer type [-Werror=incompatible-pointer-types]

:Testing Performed:

:QA Notes:

:Issues Addressed:
[WRQ-25420] [BUILD] lib32-apollo-master-official-ah212 #2535

Change-Id: I3b155223b682d58f51ba4ba60e3cf1a3cd04e41d
Reviewed-on: http://gpro.lge.com/c/webosose/webos-graphic-drm-test/+/414995
Reviewed-by: Martin Jansa <martin2.jansa@lgepartner.com>
Tested-by: Elvis Lee <kwangwoong.lee@lge.com>
Reviewed-by: Elvis Lee <kwangwoong.lee@lge.com>